language: python
cache:
  - pip
  - directories:
      - $HOME/AppData/Local/Temp/chocolatey
      - $HOME/.cache/torch
      - /c/miniconda/pkgs
matrix:
    include:
      - name: "Windows 10"
        os: windows
        language: shell
        install:
          - set -e
          - choco install -y gimp
          - wget https://raw.githubusercontent.com/trichter/conda4travis/latest/conda4travis.sh -O conda4travis.sh
          - mv /c/miniconda /c/miniconda_cached || true
          - source conda4travis.sh
          - rm -r /c/miniconda/pkgs; mv /c/miniconda_cached/pkgs /c/miniconda/pkgs || true
          - conda init powershell
          - powershell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
          - powershell ./install.ps1 -cpuonly
      - name: "Ubuntu 18.04"
        os: linux
        dist: bionic
        services:
          - xvfb
        install:
          - sudo apt-get update
          - sudo apt-get install -y gimp --no-install-recommends
          - ./install.sh --cpuonly
      - name: "Ubuntu 20.04 (apt)"
        os: linux
        dist: focal
        services:
          - xvfb
        install:
          - sudo apt-get update
          - sudo apt-get install -y gimp --no-install-recommends
          - ./install.sh --cpuonly
      - name: "Arch Linux"
        os: linux
        dist: focal
        services:
          - docker
        before_install:
          - docker run -d --name test-container -v $(pwd):/travis -w /travis whynothugo/makepkg:latest tail -f /dev/null
          - docker exec -t test-container sudo pacman -Syy xorg-server-xvfb --noconfirm
          - exec-docker() { docker exec -t test-container xvfb-run bash -c "$*"; }
        install:
          - exec-docker sudo pacman -S gimp lsb-release --noconfirm
          - exec-docker sudo chown notroot:notroot . -R
          - exec-docker ./install.sh
        script:
          - exec-docker timeout 60 tests/test.sh
branches:
  only:
  - master
script:
- timeout 60 tests/test.sh
notifications:
  email: false
